### ISSUE TITLE
Всегда ли int?

### ISSUE THREAD

**Issue by coursar** [AliAlievALive/RollsCalculation#1]
https://github.com/AliAlievALive/RollsCalculation/blob/d3b218a3001fcace8ae821d6f3ec81dbec17799a/src/RollsCalculation.java#L3-L4

**Comment by AliAlievALive** [comment]
Нет, переделаю на double

**Comment by AliAlievALive** [comment]
Исправил, а также добавил несколько изменений

**Comment by coursar** [comment]
Issue надо замечать сообщениями коммитов
